name: env_py37
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - certifi
  - numpy
  - opencv=4.6.0
  - packaging
  - ply
  - pyqt=5.15.7
  - pyqt5-sip
  - sip
  - toml
  - pytorch=1.11.0
  - typing_extensions
  - sqlite
  - py-opencv
  - pip
  - pcre2
  - openssl
  - openh264
